CREATE DATABASE TheFakeShop;

USE TheFakeShop;

CREATE TABLE Categories (
	CategoryID INT IDENTITY(1,1) PRIMARY KEY,
	CategoryName NVARCHAR(100),
	ParentID INT,
	Created_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	FOREIGN KEY(ParentID) REFERENCES Categories(CategoryID)
);

CREATE TABLE Products (
	ProductID INT IDENTITY(1,1) PRIMARY KEY,
	ProductName NVARCHAR(200),
	Price MONEY,
	InStock INT,
	Description VARCHAR(1000),
	CategoryID INT,
	Created_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	FOREIGN KEY(CategoryID) REFERENCES Categories(CategoryID)
);

CREATE TABLE ProductImages (
	PImageID INT IDENTITY(1,1) PRIMARY KEY,
	ImageLink VARCHAR(100),
	ProductID INT,
	Created_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	FOREIGN KEY(ProductID) REFERENCES Products(ProductID)
);

CREATE TABLE ProductRatings (
	PRatingID INT IDENTITY(1,1) PRIMARY KEY,
	CustomerName NVARCHAR(20), --3~20 character
	CustomerEmail VARCHAR(50),
	Rating TINYINT,
	Title NVARCHAR(50),
	Content NVARCHAR(500),
	ProductID INT,
	Created_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	FOREIGN KEY(ProductID) REFERENCES Products(ProductID)
);




