name: .NET

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master,develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet: [ '5.0.x', '6.0.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: cd src; dotnet restore
    - name: Build
      run: cd src; dotnet build --no-restore
    - name: Test
      run: cd src; dotnet test --no-build --verbosity normal
